---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: food
products: Canned salmon, Pork chops, Grandma's cookies

---
spring:
  profiles: electronics
products: not-so-smart TV, iron, vacuum-cleaner
s